trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build FirstJob
  - job: SecondJob
    steps:
    - bash: echo build SecondJob
- stage: dev
  dependsOn: build
  jobs:
   - job: OneJob
     steps:
     - bash: echo dev OneJob





